language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

sudo: false

cache:
   directories:
    - $HOME/.composer/cache

matrix:
  allow_failures:
    - php: hhvm

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source --dev

script:
  - php vendor/bin/phpspec run -fpretty
